config/routes.rb
Rails.application.routes.draw do
  get "borrowings/create"
  get "borrowings/return"
  get "books/index"
  get "books/show"
  get "books/new"
  get "books/create"
  get "books/edit"
  get "books/update"
  get "books/destroy"

  resources :books do
    member do
      get 'borrow'
      post 'return'
    end
  end
  resources :borrowings, only: [:index]
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :borrowings, dependent: :destroy
    validates :title, presence: true
    validates :author, presence: true
  end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :book
  validates :borrower_name, presence: true
  validates :borrow_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre)
  end
end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    if @book.borrowings.where(return_date: nil).exists?
      redirect_to @book, alert: 'This book is already borrowed.'
    else
      @borrowing = @book.borrowings.build(borrowing_params)
      if @borrowing.save
        redirect_to @book, notice: 'Book was successfully borrowed.'
      else
        redirect_to @book, alert: 'Failed to borrow book.'
      end
    end
  end

  def return
    @book = Book.find(params[:book_id])
    @borrowing = @book.borrowings.where(return_date: nil).first
    if @borrowing&.update(return_date: Date.today)
      redirect_to @book, notice: 'Book was successfully returned.'
    else
      redirect_to @book, alert: 'Failed to return book.'
    end
  end

  private

  def borrowing_params
    params.require(:borrowing).permit(:borrower_name, :borrow_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/views/books/_borrow_form.html.erb
<%= form_with(url: borrow_book_path(@book), method: :post, local: true) do |form| %>
    <div>
      <%= form.label :borrower_name, 'Borrower Name' %>
      <%= form.text_field :borrower_name %>
    </div>
    <div>
      <%= form.submit 'Borrow' %>
    </div>
  <% end %>

app/views/books/_return_form.html.erb
<%= form_with(url: return_book_path(@book), method: :post, local: true) do |form| %>
    <div>
      <%= form.submit 'Return' %>
    </div>
  <% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= form_with(model: @book, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div>
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<%= link_to 'New Book', new_book_path %>
<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book_path(book) %>
      <%= link_to 'Edit', edit_book_path(book) %>
      <%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with(model: @book, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div>
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><strong>Author:</strong> <%= @book.author %></p>
<p><strong>Genre:</strong> <%= @book.genre %></p>
<h2>Borrowing History</h2>
<ul>
  <% @book.borrowings.each do |borrowing| %>
    <li>
      <%= borrowing.borrower_name %> borrowed on <%= borrowing.borrow_date %>
      <% if borrowing.return_date %>
        and returned on <%= borrowing.return_date %>
      <% else %>
        and has not returned yet
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to 'Borrow', borrow_book_path(@book), method: :get %>
<%= link_to 'Return', return_book_path(@book), method: :post %>
<%= link_to 'Back', books_path %>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/borrowings/create.html.erb
<h1>Borrowings#create</h1>
<p>Find me in app/views/borrowings/create.html.erb</p>

app/views/borrowings/return.html.erb
<h1>Borrowings#return</h1>
<p>Find me in app/views/borrowings/return.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book Lending Library" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>